### ISSUE TITLE
Latent Space Interpolation

### ISSUE THREAD

**Issue by gregkocher** [zck119/3dgan-release#3]
Looking for clarification on latent space interpolation from your paper:

For WITHIN class interpolation (e.g. chair type1 <-> chair type2) you can use the generator network that was trained on that single object category (e.g. the chair generator network). 

But for BETWEEN class latent space interpolation, am I right in assuming that you trained the network on the union of the category1 category2 datasets (e.g. cars and boats), and then use that generator network's latent vectors and 3D generated objects? So to interpolate between two distinct categories, you must train a new network on the union of those data sets? 
In your paper you used cars and boats. Was this choice because that paring had better results than other pairings, and if so, do you think inter-class interpolation will work best when the 2 object categories are somewhat similar (e.g. the bounding boxes of cars and boats are basically shoe box shaped so going between them is easier than going from a car to a chair, which typically has bounding boxes that are more cube shaped so has different relative dimensions)? Or was the choice because it is arguably more semantically meaningful to go between 2 vehicle types (car-boat) than e.g. an airplane to a cup?

**Comment by eriche2016** [comment]
i have the same doubt. By the way,  will the author release the training code?

**Comment by gregkocher** [comment]
For anyone else still wondering:

For between category interpolation, they trained on a dataset made of the union of some of the categories with the most training examples, which of course needed to include the 2 categories they were interpolating between [in the paper and animations: car/boat].


Also, check out TensorFlow implementation doing within category latent space interpolations at:
https://github.com/rp2707/coms4995-project

e.g. some airplanes and chairs [which don't look nearly as good as the ones in this paper but are still interesting]:
https://github.com/rp2707/coms4995-project/blob/master/example_output/airplane_output/interpolation/ANIMATION_airplane_interpolation.gif

https://github.com/rp2707/coms4995-project/blob/master/example_output/chair_output_examples/interpolation/ANIMATION_chairs_interplation.gif

https://github.com/rp2707/coms4995-project/blob/master/example_output/chair_output_examples/interpolation2/ANIMATION_CHAIRS2.gif
