### ISSUE TITLE
 module 'nn' not found

### ISSUE THREAD

**Issue by ashishgupta2598** [zck119/3dgan-release#7]
I tried running the code but its showing this error
```
> 	no field package.preload['nn']
	no file './nn.lua'
	no file '/usr/share/luajit-2.1.0-beta3/nn.lua'
	no file '/usr/local/share/lua/5.1/nn.lua'
	no file '/usr/local/share/lua/5.1/nn/init.lua'
	no file '/usr/share/lua/5.1/nn.lua'
	no file '/usr/share/lua/5.1/nn/init.lua'
	no file './nn.so'
	no file '/usr/local/lib/lua/5.1/nn.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/nn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.1/trepl/init.lua:389: in function 'require'
	main.lua:1: in main chunk
	[C]: in function 'dofile'
	/usr/lib/torch-trepl/th:149: in main chunk
	[C]: at 0x561c0f12c1d0
```
I have pytorch installed.

**Comment by jiajunwu** [comment]
Hi this code depends on Torch and is written in Lua.

Best,
Jiajun

**Comment by ashishgupta2598** [comment]
Hii,
Thanks for your reply. But Can you help me with this error. I simply followed the steps ```th main.lua -gpu 0 -class chair``` but it shows that error(nn module not found)

**Comment by AlexMuresan** [comment]
@ashishgupta2598 do you have all the prerequisites installed?

**Comment by ashishgupta2598** [comment]
Yes I have everything installed.

**Comment by ashishgupta2598** [comment]
And by everything you means pytorch with python 3.x. and  lua packages too.
Please specify if any other packages required.

**Comment by AlexMuresan** [comment]
As I understand it this project doesn't use the pytorch library. It uses the original torch. You can find it [here](http://torch.ch/). You need to read the prerequisites in the README.md more carefully. It specifies everything you need.

I'll paste here the prerequisites so you can take a better look at them:

## Prerequisites
#### Torch
We use Torch 7 (http://torch.ch) for our implementation with these additional packages:

- [`matio`](https://github.com/soumith/matio-ffi.torch) or [`fb.mattorch`](https://github.com/facebook/fblualib/tree/master/fblualib/mattorch): we use `.mat` file for saving voxelized shapes.

#### Visualization
- Basic visualization: MATLAB (tested on R2016b)
- Advanced visualization: Python 2.7 with package `numpy`, `matplotlib`, `scipy` and `vtk` (version 5.10.1)

**Note**: for advanced visualization, the version of `vtk` has to be 5.10.1, not above. It is available in the package list of common Python distributions like [Anaconda](https://docs.continuum.io/anaconda/old-pkg-lists/2.3.0/py27)
